pipeline {
    agent any

    environment {
        IMAGE_NAME = "lordson19/terraform-docker"
        TAG = "latest"
        TF_VAR_private_key_path = "/var/lib/jenkins/.ssh/node.pem"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/LORDSON11/learn-jenkins.git', branch: 'main'
            }
        }

        stage('Terraform Init & Apply') {
            steps {
                dir('terraform-docker/terraform') {
                    sh '''
                        terraform init
                        terraform apply -auto-approve
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$TAG .'
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
                        echo "$PASS" | docker login -u "$USER" --password-stdin
                        docker push $IMAGE_NAME:$TAG
                    '''
                }
            }
        }
    }
}
