pipeline{
    agent any 
    stages{
        stage('Clone Repository'){
            steps{
                git url : 'https://github.com/LORDSON11/learn-jenkins.git'
            }
        }
        stage('Build Docker Image'){
            steps{
                script {
                    docker.build('myimage')
                }
            }
        }
    }
}